server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/voice_temp?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
#    url: jdbc:mysql://xxx:3306/voice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
#    username: root
#    password: xxx
#    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.kfs.voice.entity
  mapper-locations:
    - classpath:mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  header: "Authorization"
  tokenPrefix: "Bearer "
  secret: "kfsvoicetool"
  expireTime: 120

voice:
  path: /Users/chenzhihang/Documents/upload/
#  path: D:\\upload\\